Set-StrictMode -Version 2.0
function Connect-ChaseHQ { [CmdletBinding()] param([string]$HostName='127.0.0.1',[int]$Port=37680) [pscustomobject]@{ BaseUri="http://${HostName}:$Port/api/v1"; Host=$HostName; Port=$Port } }
function Invoke-ChaseHQApi { param($Connection,[string]$Path,[string]$Method='GET',$Body=$null) $u="$($Connection.BaseUri)/$($Path.TrimStart('/'))"; $p=@{Uri=$u;Method=$Method}; if($null-ne $Body){$p.ContentType='application/json';$p.Body=($Body|ConvertTo-Json -Depth 20 -Compress)}; Invoke-RestMethod @p }
function Get-ChaseHQStatus { param($Connection) Invoke-ChaseHQApi $Connection 'status' }
function Get-ChaseHQCapabilities { param($Connection) Invoke-ChaseHQApi $Connection 'capabilities' }
function Get-ChaseHQApiSchema { param($Connection) Invoke-ChaseHQApi $Connection 'schema' }
function Pause-ChaseHQ { param($Connection) Invoke-ChaseHQApi $Connection 'control/pause' 'POST' @{} }
function Resume-ChaseHQ { param($Connection) Invoke-ChaseHQApi $Connection 'control/resume' 'POST' @{} }
function Step-ChaseHQFrame { param($Connection,[int]$Frames=1) Invoke-ChaseHQApi $Connection 'control/step-frame' 'POST' @{frames=$Frames} }
function Step-ChaseHQInstruction { param($Connection,[ValidateSet('A','B')]$Cpu='A') Invoke-ChaseHQApi $Connection 'control/step-instruction' 'POST' @{cpu=$Cpu} }
function Invoke-ChaseHQIocPulse { param($Connection,[int]$Port,[string]$Mask,[int]$Frames=3) Invoke-ChaseHQApi $Connection 'input/ioc/pulse' 'POST' @{port=$Port;mask=$Mask;frames=$Frames} }
function Get-ChaseHQMemory { param($Connection,[ValidateSet('A','B')]$Cpu='A',[string]$Address,[ValidateSet(8,16,32)]$Width=16) Invoke-ChaseHQApi $Connection "memory/$Cpu/$Address?width=$Width" }
function Invoke-ChaseHQCommand { param($Connection,[Parameter(Mandatory)][string]$Command) Invoke-ChaseHQApi $Connection 'command' 'POST' @{command=$Command} }
function Export-ChaseHQMemory { param($Connection,[ValidateSet('A','B')]$Cpu='A',[string]$Start,[string]$End,[Parameter(Mandatory)][string]$Path) $u="$($Connection.BaseUri)/export/memory?cpu=$Cpu&start=$Start&end=$End"; Invoke-WebRequest -Uri $u -OutFile $Path; Get-Item $Path }
function Save-ChaseHQEvidence { param($Connection,[string]$Name=('evidence-'+(Get-Date -Format 'yyyyMMdd-HHmmss'))) Invoke-ChaseHQApi $Connection 'evidence/capture' 'POST' @{name=$Name} }
function Save-ChaseHQMemorySnapshot { [CmdletBinding()] param($Connection,[Parameter(Mandatory)][string]$Name,[ValidateSet('A','B')]$Cpu='A',[Parameter(Mandatory)][string]$Start,[Parameter(Mandatory)][string]$End,[string]$Root='.\evidence\memory') New-Item -ItemType Directory -Force -Path $Root|Out-Null; $bin=Join-Path $Root "$Name-$Cpu-$Start-$End.bin"; Export-ChaseHQMemory $Connection $Cpu $Start $End $bin|Out-Null; $status=Get-ChaseHQStatus $Connection; $meta=[ordered]@{schema='chq-memory-snapshot-v1';name=$Name;captured=(Get-Date).ToString('o');cpu=$Cpu;start=$Start;end=$End;file=(Split-Path $bin -Leaf);status=$status}; $meta|ConvertTo-Json -Depth 12|Set-Content (Join-Path $Root "$Name-$Cpu-$Start-$End.json") -Encoding UTF8; Get-Item $bin }
function Compare-ChaseHQMemoryFiles { [CmdletBinding()] param([Parameter(Mandatory)][string]$Before,[Parameter(Mandatory)][string]$After,[uint32]$BaseAddress=0,[string]$OutFile) $a=[IO.File]::ReadAllBytes((Resolve-Path $Before));$b=[IO.File]::ReadAllBytes((Resolve-Path $After));if($a.Length-ne$b.Length){throw 'Memory files must be equal length'};$rows=for($i=0;$i-lt$a.Length;$i++){if($a[$i]-ne$b[$i]){[pscustomobject]@{Offset=('0x{0:X}'-f$i);Address=('0x{0:X}'-f($BaseAddress+$i));Before=('0x{0:X2}'-f$a[$i]);After=('0x{0:X2}'-f$b[$i]);Delta=([int]$b[$i]-[int]$a[$i]);Xor=('0x{0:X2}'-f($a[$i]-bxor$b[$i]))}}};if($OutFile){$rows|Export-Csv -NoTypeInformation $OutFile};$rows }
function Add-ChaseHQAnnotation { [CmdletBinding()] param([Parameter(Mandatory)][string]$Root,[Parameter(Mandatory)][ValidateSet('frame','memory','routine','sprite','checkpoint','experiment','event')]$Kind,[Parameter(Mandatory)][string]$Target,[Parameter(Mandatory)][string]$Text,[string[]]$Tags=@()) New-Item -ItemType Directory -Force -Path $Root|Out-Null;$obj=[ordered]@{schema='chq-annotation-v1';id=[guid]::NewGuid().ToString();created=(Get-Date).ToString('o');kind=$Kind;target=$Target;text=$Text;tags=@($Tags)};$path=Join-Path $Root ($obj.id+'.json');$obj|ConvertTo-Json -Depth 8|Set-Content $path -Encoding UTF8;Get-Item $path }

function Get-ChaseHQHandling { param($Connection) Invoke-ChaseHQApi $Connection 'tuning/handling' }
function Set-ChaseHQHandling { param($Connection,[double]$Cornering=1.0,[double]$SpeedRetain=1.0) Invoke-ChaseHQApi $Connection 'tuning/handling' 'PUT' @{cornering=$Cornering;speedRetain=$SpeedRetain} }
function Reset-ChaseHQHandling { param($Connection) Invoke-ChaseHQApi $Connection 'tuning/handling' 'DELETE' }
function Get-ChaseHQPaletteBank { param($Connection,[ValidateRange(0,255)][int]$Bank) Invoke-ChaseHQApi $Connection "palette/$Bank" }
function Set-ChaseHQPaletteEntry { param($Connection,[ValidateRange(0,4095)][int]$Index,[Parameter(Mandatory)][string]$Raw) Invoke-ChaseHQApi $Connection "palette/entry/$Index" 'PUT' @{raw=$Raw} }
function Reset-ChaseHQPaletteEntry { param($Connection,[ValidateRange(0,4095)][int]$Index) Invoke-ChaseHQApi $Connection "palette/entry/$Index" 'DELETE' }
function Set-ChaseHQIocHeldMask { param($Connection,[ValidateRange(0,15)][int]$Port,[Parameter(Mandatory)][string]$Mask) Invoke-ChaseHQApi $Connection 'input/ioc/xor' 'PUT' @{port=$Port;mask=$Mask} }
function Clear-ChaseHQIocHeldMasks { param($Connection) Invoke-ChaseHQApi $Connection 'input/ioc/xor' 'DELETE' }

function Get-ChaseHQCheckpoints { param($Connection) Invoke-ChaseHQApi $Connection 'checkpoints' }
function Load-ChaseHQCheckpoint { param($Connection,[Parameter(Mandatory)][string]$File,[switch]$Paused) Invoke-ChaseHQApi $Connection 'checkpoints/load' 'POST' @{file=$File;run=(-not $Paused)} }
function Invoke-ChaseHQIocSweep { param($Connection,[string]$Checkpoint='stage1-gameplay-2064.chqstate',[int]$Port=3,[string[]]$Masks=@('01','02','04','08','10','20','40','80'),[int]$PulseFrames=8,[int]$ObserveFrames=90) Invoke-ChaseHQApi $Connection 'input/ioc/sweep' 'POST' @{checkpoint=$Checkpoint;port=$Port;masks=$Masks;pulseFrames=$PulseFrames;observeFrames=$ObserveFrames} }
function Set-ChaseHQTimerFrozen { param($Connection,[bool]$Frozen=$true) if($Frozen){Invoke-ChaseHQApi $Connection 'control/timer-freeze' 'PUT' @{}}else{Invoke-ChaseHQApi $Connection 'control/timer-freeze' 'DELETE'} }
function Set-ChaseHQAlwaysOnTop { param($Connection,[bool]$Enabled=$true) Invoke-ChaseHQApi $Connection 'window/always-on-top' 'PUT' @{enabled=$Enabled} }
Export-ModuleMember -Function Connect-ChaseHQ,Invoke-ChaseHQApi,Get-ChaseHQStatus,Get-ChaseHQCapabilities,Get-ChaseHQApiSchema,Pause-ChaseHQ,Resume-ChaseHQ,Step-ChaseHQFrame,Step-ChaseHQInstruction,Invoke-ChaseHQIocPulse,Get-ChaseHQMemory,Invoke-ChaseHQCommand,Export-ChaseHQMemory,Save-ChaseHQEvidence,Save-ChaseHQMemorySnapshot,Compare-ChaseHQMemoryFiles,Add-ChaseHQAnnotation,Get-ChaseHQHandling,Set-ChaseHQHandling,Reset-ChaseHQHandling,Get-ChaseHQPaletteBank,Set-ChaseHQPaletteEntry,Reset-ChaseHQPaletteEntry,Set-ChaseHQIocHeldMask,Clear-ChaseHQIocHeldMasks,Get-ChaseHQCheckpoints,Load-ChaseHQCheckpoint,Invoke-ChaseHQIocSweep,Set-ChaseHQTimerFrozen,Set-ChaseHQAlwaysOnTop
